version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    links: 
      - db
    environment:
      PGHOST: db
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: docker
      PGPORT: 5432
      PYTHONPATH: '/workspace/scripts/'
    depends_on:
      - db 
        #condition: service_healthy

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: docker

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ~/.pgadmincompose:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: docker
        PGADMIN_DEFAULT_PASSWORD: docker
        PGADMIN_LISTEN_PORT: 80  