version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    links: 
      - db
    environment:
      PGHOST: db
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: docker
      PGPORT: 5432
      PYTHONPATH: '/workspace/scripts/'
    depends_on:
      - db 
        #condition: service_healthy
  db:
    image: postgres
    restart: unless-stopped

    environment:
      POSTGRES_PASSWORD: docker
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - 8080:80
 
    volumes:
      - ~/.pgadmincompose:/var/lib/pgadmin

    environment:
        PGADMIN_DEFAULT_EMAIL: docker
        PGADMIN_DEFAULT_PASSWORD: docker
        PGADMIN_LISTEN_PORT: 80  